### ISSUE TITLE
Google drive link down

### ISSUE THREAD

**Issue by Madouura** [Aman9das/Waydroid_Setup_Guide#2]
https://drive.google.com/file/d/1sXxng8ALWEK3Yjg4BVvU_Xy1NJcUdFV1/view?usp=drivesdk is unavailable.

**Comment by Aman9das** [comment]
Thanks for pointing this out 😅 

~~I have asked Jon West, and am uploading it myself as i type. Note that this will be sorta a hack, you're downloading stuff provided by a random internet stranger, afterall..~~

~~but it will work.~~

Got a newer image! updating guide..

**Comment by Madouura** [comment]
Thanks!
