### ISSUE TITLE
[Compatibility Check] Sky: Children of the Light

### ISSUE THREAD

**Issue by milroneth** [Aman9das/Waydroid_Setup_Guide#6]
Any chance `Sky: Children of the Light` can be tested? As far as I know, It's ARM64 only, Vulkan only, no other build is provided. Would be very interesting if it actually can be run on a PC.

**Comment by Aman9das** [comment]
Sure! My graduation exams are going on right now, so you will have to wait a few days..

**Comment by milroneth** [comment]
Of course, good luck with your exams!!

**Comment by SSUPII** [comment]
Good luck on your exams!

**Comment by kun-codes** [comment]
any updates?

**Comment by kun-codes** [comment]
any update?

**Comment by Aman9das** [comment]
The last year's waydroid android 11 build is out of date at the moment. Linux kernel removed ashmem support. This i am unable to test the games anymore.. we should wait for official or at least newer image..
